[package]
name = "maker-registry"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bincode = "1.3"
pinocchio = {version = "0.10.1", features = ["cpi", "copy"]}
pinocchio-pubkey = "0.3.0"
pinocchio-system = "0.5.0"
solana-loader-v3-interface = { version = "3.0.0", features = ["serde"] }
solana-program-error = "3.0.1"
solana-program-log = "1.1.0"
wincode = { version = "0.5.3", default-features = false, features = ["alloc", "derive"] }


[dev-dependencies]
mollusk-svm = "0.5.0"
mollusk-svm-result = "0.5.0"
solana-account = "2.2"
solana-instruction = "2.2"
solana-program-test = "2.2"
solana-pubkey = "2.2"
solana-sdk = "2.2"
solana-sdk-ids = "2.2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[[test]]
name = "integration_program_test"
path = "tests/integration/program_test.rs"
